package com.gogoy.utils

object Constant {
    //Api Request
    const val API_REQUEST_HEADER_NAME_AUTHORIZATION = "Authorization"
    const val API_REQUEST_PARAM_NAME_BADGE = "foto"
    const val API_REQUEST_PARAM_NAME_CONTENT_TYPE = "Content-Type"
    const val API_REQUEST_PARAM_NAME_DISPLAY_NAME = "name"
    const val API_REQUEST_PARAM_NAME_EMAIL = "email"
    const val API_REQUEST_PARAM_NAME_OTP = "token"
    const val API_REQUEST_PARAM_NAME_PASSWORD = "password"
    const val API_REQUEST_PARAM_NAME_PASSWORD_CONFIRM = "confirm_password"
    const val API_REQUEST_PARAM_NAME_PHONE = "no_hp"
    const val API_REQUEST_PARAM_VALUE_AOX = "application/x-www-form-urlencoded"

    //Api Response
    const val API_RESPONSE_BODY_CONTENT = "contents"
    const val API_RESPONSE_BODY_ERROR = "errors"
    const val API_RESPONSE_BODY_ITEM = "item"
    const val API_RESPONSE_BODY_ITEMS = "items"
    const val API_RESPONSE_BODY_MESSAGE = "message"
    const val API_RESPONSE_BODY_STATUS = "status"
    const val API_RESPONSE_FIELD_BADGE = "foto"
    const val API_RESPONSE_FIELD_CATEGORY = "category"
    const val API_RESPONSE_FIELD_CREATED_AT = "created_at"
    const val API_RESPONSE_FIELD_DESC = "deskripsi"
    const val API_RESPONSE_FIELD_DEVICE_ID = "deviceId"
    const val API_RESPONSE_FIELD_DIMENSION = "dimensi"
    const val API_RESPONSE_FIELD_DISPLAY_NAME = "name"
    const val API_RESPONSE_FIELD_EMAIL = "email"
    const val API_RESPONSE_FIELD_ID = "_id"
    const val API_RESPONSE_FIELD_INFO = "info"
    const val API_RESPONSE_FIELD_ITEM_NAME = "nama_brg"
    const val API_RESPONSE_FIELD_OWNER_ID = "id_user"
    const val API_RESPONSE_FIELD_PASSWORD = "password"
    const val API_RESPONSE_FIELD_PHONE = "no_hp"
    const val API_RESPONSE_FIELD_PRICE = "harga"
    const val API_RESPONSE_FIELD_PRICE_DISCOUNT = "hargadiskon"
    const val API_RESPONSE_FIELD_STATUS = "status"
    const val API_RESPONSE_FIELD_STOCK = "stok"
    const val API_RESPONSE_FIELD_TOKEN = "api_token"
    const val API_RESPONSE_FIELD_UNIT = "satuan"
    const val API_RESPONSE_FIELD_UPDATED_AT = "updated_at"

    //ID
    const val ID_ITEM_ALL_KOMODITI = 1
    const val ID_ITEM_ALL_PROMO_KOMODITI = 2
    const val ID_ITEM_ALL_PROMO_SAYUR = 3
    const val ID_ITEM_ALL_SAYUR = 4

    //Uppercase
    const val ACTIVITY_BEFORE = "ACTIVITY_BEFORE"
    const val ACTIVITY_CART = "ACTIVITY_CART"
    const val ACTIVITY_CART_BACK = "ACTIVITY_CART_BACK"
    const val ACTIVITY_ITEM = "ACTIVITY_ITEM"
    const val ACTIVITY_MAIN = "ACTIVITY_MAIN"
    const val CODE_ERROR_BAD_REQUEST = "BAD_REQUEST"
    const val CODE_ERROR_NETWORK = "NETWORK"
    const val CODE_ERROR_PARSE = "PARSE"
    const val CODE_ERROR_UNAUTHORIZED = "UNAUTHORIZED"
    const val UP_AMOUNT = "AMOUNT"
    const val UP_BADGE = "BADGE"
    const val UP_CLASS_QUALIFIED = "CLASS_QUALIFIED"
    const val UP_DEVICE = "DEVICE"
    const val UP_ERROR = "ERROR"
    const val UP_FUNCTION = "FUNCTION"
    const val UP_ID = "ID"
    const val UP_IDS = "IDS"
    const val UP_INPUT = "INPUT"
    const val UP_ITEM_NAME = "ITEM_NAME"
    const val UP_DATA_ITEM = "DATA_ITEM"
    const val UP_TEST_DATA_ITEM = "TEST_DATA_ITEM"
    const val UP_DATA_USER = "DATA_USER"
    const val UP_DESC = "DESC"
    const val UP_DISPLAY_NAME = "DISPLAY_NAME"
    const val UP_EMAIL = "EMAIL"
    const val UP_INFO = "INFO"
    const val UP_NAME = "NAME"
    const val UP_OWNER = "OWNER"
    const val UP_PRICE = "PRICE"
    const val UP_PHONE_NUMBER = "PHONE_NUMBER"
    const val UP_SDK_VERSION = "SDK_VERSION"
    const val UP_TITLE = "TITLE"
    const val UP_TOKEN = "TOKEN"
    const val UP_TOKEN_AUTH = "AUTH_TOKEN"
    const val UP_TYPE_ID = "TYPE_ID"

    //URL
    const val SENTRY_DSN = "https://a5b4bbba2c1d438793b03d2f434a6fb9@sentry.io/1421260"
    private const val URL_ROOT = "https://api-gogoy.oemahsolution.com/"
    const val URL_AUTH_LOGIN = URL_ROOT + "auth/login"
    const val URL_AUTH_LOGOUT = URL_ROOT + "auth/logout"
    const val URL_AUTH_REGISTER = URL_ROOT + "auth/register"
    const val URL_BANNER = URL_ROOT + "banner/viewbanner"
    const val URL_ITEM_ALL_KOMODITI = URL_ROOT + "item/allkomoditi"
    const val URL_ITEM_ALL_PROMO_KOMODITI = URL_ROOT + "item/allpromokomoditi"
    const val URL_ITEM_ALL_PROMO_SAYUR = URL_ROOT + "item/allpromosayur"
    const val URL_ITEM_ALL_SAYUR = URL_ROOT + "item/allsayur"
    const val URL_ITEM_DETAIL = URL_ROOT + "item/detail/"
    const val URL_ITEM_PROMO_KOMODITI = URL_ROOT + "item/promokomoditi"
    const val URL_ITEM_PROMO_SAYUR = URL_ROOT + "item/promosayur"
    const val URL_ITEM_RELATED = URL_ROOT + "item/terkait/"
    const val URL_RESET_NEW_PASSWORD = URL_ROOT + "forgot"
    const val URL_RESET_SEND_CODE = URL_ROOT + "resetpassword"
    const val URL_RESET_VERIFY_CODE = URL_ROOT + "find"
    const val URL_USER_EDIT_PROFILE = URL_ROOT + "user/edit"
    const val URL_USER_PROFILE = URL_ROOT + "user/profile"

    //other
    const val NULL = "null"
}